// Builds the single-file web app into docs/ (used by GitHub Pages and the Android app)
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.join(__dirname, '..');
const pkg = require(path.join(root, 'package.json'));
const out = path.join(root, 'docs');
fs.mkdirSync(out, { recursive: true });

let html = fs.readFileSync(path.join(root, 'src/index.html'), 'utf8');
const mathjs = fs.readFileSync(require.resolve('mathjs/lib/browser/math.js'), 'utf8')
  .replace(/\/\/# sourceMappingURL=.*$/m, '').replace(/<\/script/gi, '<\\/script');
html = html.replace('/*MATHJS_INLINE*/', () => '/* math.js 11.8.0 | Apache-2.0 | https://mathjs.org */\n' + mathjs);
html = html.replace(/version: '[\d.]+'/, `version: '${pkg.version}'`).replace(/build: 0,/, `build: ${parseInt(process.env.BUILD_NUMBER || '0', 10) || 0},`);
const cap = fs.readFileSync(require.resolve('@capacitor/core/dist/capacitor.js'), 'utf8').replace(/\/\/# sourceMappingURL=.*$/m, '').replace(/<\/script/gi, '<\\/script');
html = html.replace('/*CAPACITOR_INLINE*/', () => cap);
const qrLib = fs.readFileSync(require.resolve('qrcode-generator/qrcode.js'), 'utf8').replace(/<\/script/gi, '<\\/script');
html = html.replace('/*QR_INLINE*/', () => '/* qrcode-generator 1.4.4 | MIT | Kazuhiko Arase */\n' + qrLib);
html = html.replace('/*KHATA_CSS*/', () => fs.readFileSync(path.join(root, 'src/khata.css'), 'utf8'));
html = html.replace('/*KHATA_JS*/', () => (['khata.js', 'backup.js', 'pdf.js'].map(f => fs.readFileSync(path.join(root, 'src', f), 'utf8')).join('\n')).replace(/<\/script/gi, '<\\/script'));
fs.writeFileSync(path.join(out, 'index.html'), html);
// the page a customer opens from the khata link (data travels inside the link after #)
fs.mkdirSync(path.join(out, 'k'), { recursive: true });
fs.writeFileSync(path.join(out, 'k', 'index.html'), fs.readFileSync(path.join(root, 'src/khata-view.html'), 'utf8').replace('/*QR_INLINE*/', () => qrLib));
fs.writeFileSync(path.join(out, 'k', 'ok.txt'), 'ok\n');

fs.copyFileSync(path.join(root, 'assets/icon.svg'), path.join(out, 'icon.svg'));
fs.writeFileSync(path.join(out, 'manifest.webmanifest'), JSON.stringify({
  name: 'CalcNote Freedom', short_name: 'CalcNote', start_url: './', scope: './', display: 'standalone',
  background_color: '#F3F9F3', theme_color: '#66BB6A', description: 'Notepad calculator that works offline',
  icons: [{ src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any maskable' }, { src: 'icon-512.png', sizes: '512x512', type: 'image/png' }]
}, null, 2));
const png = path.join(root, 'assets/icon-512.png');
if (fs.existsSync(png)) fs.copyFileSync(png, path.join(out, 'icon-512.png'));

const hash = crypto.createHash('sha1').update(html).digest('hex').slice(0, 10);
fs.writeFileSync(path.join(out, 'sw.js'), `// offline cache – generated by scripts/build.js
const CACHE = 'cnf-${pkg.version}-${hash}';
const FILES = ['./', './index.html', './manifest.webmanifest', './icon.svg'];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(r => r || fetch(e.request).then(res => { const copy = res.clone(); caches.open(CACHE).then(c => c.put(e.request, copy)); return res; })));
});
`);
fs.writeFileSync(path.join(out, '.nojekyll'), '');
console.log(`Built docs/index.html (${(html.length / 1024).toFixed(0)} KB) v${pkg.version}`);
